import { decryptSecret, encryptSecret } from './crypto';
import { supabaseAdmin } from './supabase-admin';

const GRAPH='https://graph.microsoft.com/v1.0';
export const MICROSOFT_SCOPES='openid profile email offline_access Files.ReadWrite';

export function microsoftAuthorizeUrl(slot:string,state:string){
  const p=new URLSearchParams({client_id:process.env.MICROSOFT_CLIENT_ID||'',response_type:'code',redirect_uri:`${process.env.APP_URL}/api/onedrive/callback`,response_mode:'query',scope:MICROSOFT_SCOPES,state,prompt:'select_account'});
  p.set('state',`${slot}.${state}`); return `https://login.microsoftonline.com/common/oauth2/v2.0/authorize?${p}`;
}
export async function redeemCode(code:string){
  const body=new URLSearchParams({client_id:process.env.MICROSOFT_CLIENT_ID||'',client_secret:process.env.MICROSOFT_CLIENT_SECRET||'',code,redirect_uri:`${process.env.APP_URL}/api/onedrive/callback`,grant_type:'authorization_code',scope:MICROSOFT_SCOPES});
  const r=await fetch('https://login.microsoftonline.com/common/oauth2/v2.0/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body,cache:'no-store'}); if(!r.ok) throw new Error(`Microsoft token error ${r.status}`); return r.json() as Promise<{access_token:string;refresh_token?:string;expires_in:number}>;
}
export async function graphMe(access:string){ const r=await fetch(`${GRAPH}/me?$select=id,displayName,userPrincipalName,mail`,{headers:{Authorization:`Bearer ${access}`},cache:'no-store'}); if(!r.ok)throw new Error('Graph /me failed'); return r.json(); }
export async function graphDrive(access:string){ const r=await fetch(`${GRAPH}/me/drive?$select=id,driveType,webUrl,owner`,{headers:{Authorization:`Bearer ${access}`},cache:'no-store'}); if(!r.ok)throw new Error('Graph /drive failed'); return r.json(); }
export async function refreshAccess(accountId:string){ const db=supabaseAdmin(); const {data:a,error}=await db.from('onedrive_accounts').select('*').eq('id',accountId).single(); if(error||!a)throw new Error('Account missing'); if(new Date(a.access_expires_at).getTime()>Date.now()+120000)return decryptSecret(a.access_token_enc); const refresh=decryptSecret(a.refresh_token_enc); const body=new URLSearchParams({client_id:process.env.MICROSOFT_CLIENT_ID||'',client_secret:process.env.MICROSOFT_CLIENT_SECRET||'',refresh_token:refresh,grant_type:'refresh_token',scope:MICROSOFT_SCOPES}); const r=await fetch('https://login.microsoftonline.com/common/oauth2/v2.0/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body}); if(!r.ok)throw new Error('Token refresh failed'); const t=await r.json(); await db.from('onedrive_accounts').update({access_token_enc:encryptSecret(t.access_token),refresh_token_enc:encryptSecret(t.refresh_token||refresh),access_expires_at:new Date(Date.now()+t.expires_in*1000).toISOString()}).eq('id',accountId); return t.access_token; }
export async function listFolderPhotos(accountId:string,folderItemId='root'){ const access=await refreshAccess(accountId); const path=folderItemId==='root'?`${GRAPH}/me/drive/root/children`: `${GRAPH}/me/drive/items/${encodeURIComponent(folderItemId)}/children`; const u=new URL(path); u.searchParams.set('$select','id,name,size,createdDateTime,lastModifiedDateTime,file,image,photo,parentReference,@microsoft.graph.downloadUrl'); u.searchParams.set('$expand','thumbnails'); u.searchParams.set('$top','200'); const r=await fetch(u,{headers:{Authorization:`Bearer ${access}`},cache:'no-store'}); if(!r.ok)throw new Error(`Graph list failed ${r.status}`); const j=await r.json(); return (j.value||[]).filter((x:any)=>x.file && (x.image||x.photo)); }
export async function deleteDriveItem(accountId:string,itemId:string){ const access=await refreshAccess(accountId); const r=await fetch(`${GRAPH}/me/drive/items/${encodeURIComponent(itemId)}`,{method:'DELETE',headers:{Authorization:`Bearer ${access}`}}); if(r.status!==204)throw new Error(`Delete failed ${r.status}`); }
